version: 2
# https://docs.gitguardian.com/ggshield-docs/configuration#configuration-files

secret:

  ignored_matches:
    - name: signature test key
      match: kQH5HW/8p1uGOVjbgWA7FunAmGO8lsSUXNsu3eow76sz84Q18fWxnyRzBHCd3pd5nE9qa99HAZtuZuj6F1huXg==
