module private currency_mapping

let private currency_map = Map<string, string> ([
    ("ADA", "ADA")
    ("ALGO", "ALGO")
    ("ATOM", "ATOM")
    ("BAT", "BAT")
    ("BCH", "BCH")
    ("BSV", "BSV")
    ("CHF", "CHF")
    ("DAI", "DAI")
    ("DASH", "DASH")
    ("EOS", "EOS")
    ("GNO", "GNO")
    ("ICX", "ICX")
    ("FEE", "KFEE")
    ("LINK", "LINK")
    ("LSK", "LSK")
    ("NANO", "NANO")
    ("OMG", "OMG")
    ("PAXG", "PAXG")
    ("QTUM", "QTUM")
    ("SC", "SC")
    ("USDC", "USDC")
    ("USDT", "USDT")
    ("WAVES", "WAVES")
    ("ETC", "XETC")
    ("ETH", "XETH")
    ("LTC", "XLTC")
    ("MLN", "XMLN")
    ("REP", "XREP")
    ("XTZ", "XTZ")
    ("XTZ.S", "XTZ.S")
    ("XBT", "XXBT")
    ("XDG", "XXDG")
    ("XLM", "XXLM")
    ("XMR", "XXMR")
    ("XRP", "XXRP")
    ("ZEC", "XZEC")
    ("CAD", "ZCAD")
    ("EUR", "ZEUR")
    ("GBP", "ZGBP")
    ("JPY", "ZJPY")
    ("USD", "ZUSD")
])

let private kraken_currency_map = Map<string, string>([
    ("ADA","ADA")
    ("ALGO","ALGO")
    ("ATOM","ATOM")
    ("BAT","BAT")
    ("BCH","BCH")
    ("BSV","BSV")
    ("CHF","CHF")
    ("DAI","DAI")
    ("DASH","DASH")
    ("EOS","EOS")
    ("GNO","GNO")
    ("ICX","ICX")
    ("KFEE","FEE")
    ("LINK","LINK")
    ("LSK","LSK")
    ("NANO","NANO")
    ("OMG","OMG")
    ("PAXG","PAXG")
    ("QTUM","QTUM")
    ("SC","SC")
    ("USDC","USDC")
    ("USDT","USDT")
    ("WAVES","WAVES")
    ("XETC","ETC")
    ("XETH","ETH")
    ("XLTC","LTC")
    ("XMLN","MLN")
    ("XREP","REP")
    ("XTZ","XTZ")
    ("XTZ.S","XTZ.S")
    ("XXBT","XBT")
    ("XXDG","XDG")
    ("XXLM","XLM")
    ("XXMR","XMR")
    ("XXRP","XRP")
    ("XZEC","ZEC")
    ("ZCAD","CAD")
    ("ZEUR","EUR")
    ("ZGBP","GBP")
    ("ZJPY","JPY")
    ("ZUSD","USD")
])


let get_kraken_currency currency =    
    match currency with 
    | "BTC" -> "XXBT"
    | _ -> currency_map.[currency]

let get_currency (kraken_currency:string) =
    //let uppercase = kraken_currency.ToUpper()

    match kraken_currency with 
    | "XXBT" -> "BTC"
    | _ ->
        match kraken_currency_map.TryGetValue (kraken_currency.ToUpper()) with
        | true, currency -> currency
        | _ -> failwithf "\"%s\" is not a valid Kraken currency" kraken_currency
