trigger:
- alpha

pool:
  vmImage: 'windows-latest'  

variables:
  version: "0.1"
  

steps:
- script: |
    echo "version -> $(version)"
    echo "Build.BuildNumber -> $(Build.BuildNumber)"
    echo "$VERSIONNUMBER -> $(Build.VERSIONNUMBER)"
    echo "Build.BuildId -> $(Build.BuildId)"
    echo "Build.SourceVersion -> $(Build.SourceVersion)"
    echo "Build.Rev:rrr -> $(Build.Rev:rrr) $(Rev:.rrr) $(Build.rev:.r)"
    echo "AAA -> $(Build.BuildDefinitionName)_$(Build.Date:yyyyMMdd).$(Build.BuildID).$(Build.Rev:.r)$(Build.Build.SourceBranchName)"
  displayName: 'Create version like 0.1.2.3'

