trigger:
- alpha

pool:
  vmImage: 'windows-latest'  

variables:
  version: "0.2"
  # counter that is reset to 1 every time "version" change
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-using-expressions
  #build patch: $[counter('$(version)', 1)]  
  build counter: $[counter('buildCounter',1)]
  day build counter: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]

jobs:  

- job: patch_number
  displayName: "Create Path number"
  steps:
  - powershell: echo "##vso[task.variable variable=n;isOutput=trues]123"
    name: version

- job: build
  displayName: 'Create version like 0.1.2.3'
  variables:
    build patch: $[counter($[$(version)], 1)] 
    package version: "$(version).$(build patch).$(day build counter)"
  steps:
  - script: |
      echo "version -> $(version) | package version -> $(package version)"
      echo "Build.BuildNumber -> $(Build.BuildNumber)"
      echo "$VERSIONNUMBER -> $(Build.VERSIONNUMBER)"
      echo "Build.BuildId -> $(Build.BuildId)"
      echo "Build.SourceVersion -> $(Build.SourceVersion)"
      echo "Build.Rev:rrr -> $(Build.Rev:rrr) $(Rev:.rrr) $(Build.rev:.r)"
      echo "Patch -> $(Patch) - $(Build.Patch)"
      echo "(build path) -> $(build patch)"
      echo "(build counter) -> $(build counter)"
      echo "(day build counter) -> $(day build counter)"
#    echo "(Major).(Minor).(Patch)-(Build.SourceBranchName) -> $(Major).$(Minor).$(Patch)-$(Build.SourceBranchName)"
#    echo "AAA -> $(Build.BuildDefinitionName)_$(Build.Date:yyyyMMdd).$(Build.BuildID).$(Build.Rev:.r)$(Build.Build.SourceBranchName)"
    displayName: "Create version"