trigger:
- alpha

pool:
  vmImage: 'windows-latest'  

variables:
  version: "0.1"
  

steps:
- script: |
    echo "version -> $(version)"
    echo "Build.BuildNumber -> $(Build.BuildNumber)"
    echo "$VERSIONNUMBER -> $(VERSIONNUMBER)"
    echo "Build.BuildId -> $(Build.BuildId)"
    echo "Build.SourceVersion -> $(Build.SourceVersion)"
    echo "Rev:rrr -> $(Rev:rrr)"
  displayName: 'Create version like 0.1.2.3'

