trigger:
- master

pool:
  vmImage: 'windows-latest'  

variables:
  version: "0.1"
  

steps:
- script: |
    echo "version -> $(version)"
    echo "Build.BuildNumber -> $(Build.BuildNumber)"
    echo "$VERSIONNUMBER -> $VERSIONNUMBER"
    echo "Build.BuildId -> $(Build.BuildId)"
  displayName: 'Create version like 0.1.2.3'

