trigger:
- alpha

pool:
  vmImage: 'windows-latest'  


variables:
  version: "0.3"
  # counter that is reset to 1 every time "version" change
  build number: $[counter(variables.version, 1)]
  package version: "$(version).$(build number)"
  package version long: "$(version).$(Build.BuildNumber)" 
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-variables-using-expressions
  build counter: $[counter('buildCounter',1)]
  day build counter: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]

jobs:  

#- job: patch_number
#  displayName: "Create Path number"
#  steps:
#  - powershell: echo "##vso[task.setvariable variable=n;isOutput=trues]123"
#    name: version
# access to it in another job using $[dependencies.patch_number.outputs['setvarStep.myOutputVar'] ]

- job: build
  displayName: 'Create version like 0.1.2.3'
  steps:
  - script: |
      echo "version -> $(version) | package version -> $(package version) | package version long -> $(package version long)"
      echo "Build.BuildNumber -> $(Build.BuildNumber)"
      echo "Build.BuildId -> $(Build.BuildId)"
      echo "Build.SourceVersion -> $(Build.SourceVersion)"
      echo "Patch -> $(Patch) - $(Build.Patch)"
      echo "(build path) -> $(build patch)"
      echo "(build counter) -> $(build counter)"
      echo "(day build counter) -> $(day build counter)"

#    echo "(Major).(Minor).(Patch)-(Build.SourceBranchName) -> $(Major).$(Minor).$(Patch)-$(Build.SourceBranchName)"
#    echo "AAA -> $(Build.BuildDefinitionName)_$(Build.Date:yyyyMMdd).$(Build.BuildID).$(Build.Rev:.r)$(Build.Build.SourceBranchName)"
    displayName: "Create version"