# it works also without "resources" but when chaange the repository name in GitHub it will be lost
resources:
  #containers: 
  repositories:
  - repository: GitHub
    type: github
    name: alex75it/KrakenApiClient
    endpoint: alex75it 
    # GitHub service connection name (defined in Project Settings > GitHub connections)


trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  version: "0.7"
  project file: "Alex75.KrakenApiClient/Alex75.KrakenApiClient.fsproj"
  build number: $[counter(variables.version, 1)] 
  package version: "$(version).$(build number)"
  package version long: "$(version).$(Build.BuildNumber)" 


jobs:

- job: Build
  steps: 
    - bash: echo "Build the solution $(base version)"
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs: 
        projects: "$(project file)"
        arguments: --configuration Release

- job: Test
  dependsOn: Build
  steps:
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: "**/*Tests.*proj"
        arguments: >
          --configuration Release
          --filter TestCategory!=AFFECT_BALANCE&TestCategory!=REQUIRE_API_KEY

- job: Package
  dependsOn: Test
  steps:
    - task: DotNetCoreCLI@2
      displayName: "Create package (dotnet pack)"
      inputs:
        command: pack
        arguments: --configuration Release
        packagesToPack: "$(project file)"
        versioningScheme: byEnvVar
        versionEnvVar: "package version"

    - bash: echo Created package version "$(package version)"
    
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget Alex75'


