trigger:
- master

pool:
  vmImage: 'ubuntu-latest'  

variables:
  version: "0.1"
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.    
    echo version -> $(version)
    echo Build.BuildNumber -> $(Build.BuildNumber)
    echo See https://aka.ms/yaml
  displayName: 'Check how to create a nice package version like 0.1.2.3'
