trigger:
- master

pool:
  vmImage: 'ubuntu-latest'  

variables:
  version: "0.1"
  

steps:
- script: |
    echo "version -> $(version)"
    echo "Build.BuildNumber -> $(Build.BuildNumber)"
  displayName: 'Create version like 0.1.2.3'

