# it works also without "resources"
resources:
  #containers: 
  repositories:
  - repository: GitHub
    type: github
    name: alex75it/KrakenApiClient
    endpoint: alex75it 
    # GitHub service connection name (defined in Project Settings > GitHub connections)


trigger:
- master

pool:
  vmImage: 'windows-latest'


variables:
  base version: "0.5"
  buildConfiguration: 'Release'
  project file: "Alex75.KrakenApiClient/Alex75.KrakenApiClient.fsproj"


jobs:

- job: Build
  steps: 
    - bash: echo "Build the solution $(base version)"
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs: 
        projects: "$(project file)"
        arguments: "--configuration $(buildConfiguration)"

- job: Test
  dependsOn: Build
  steps:
    - task: DotNetCoreCLI@2
      displayName:  Test
      inputs:
        command: test
        projects: "**/*[Tt]est*.*proj"
        arguments: 
          - "--configuration $(BuildConfigutration)"
          - "--filter TestCategory!=AFFECT_BALANCE"

- job: Package
  dependsOn: Test
  variables:
  - name: version
    value: '$(base version).$(Build.BuildNumber)'
  steps:
    - task: DotNetCoreCLI@2
      displayName: "Create package (dotnet pack)"
      inputs:
        command: pack
        packagesToPack: "$(project file)"
        versioningScheme: byEnvVar
        versionEnvVar: "version"

    - bash: echo Created package version "$(version)"
    
    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'Nuget Alex75'


