<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!--<TargetFrameworks>net8.0;net10.0</TargetFrameworks>-->
    <Description>Kraken API client for .Net</Description>
    <Authors>Alessandro Piccione</Authors>
    <PackageId>Alex75.KrakenApiClient</PackageId>
    <PackageIcon>logo.png</PackageIcon>
    <PackageTags>Kraken cryptocurrency XRP Bitcoin</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/alex-piccione/KrakenApiClient</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageProjectUrl>https://github.com/alex-piccione/KrakenApiClient</PackageProjectUrl>
    <UserSecretsId>Alex75.KrakenApiClient-08ccac50-5aef-4bd5-b18a-707588558352</UserSecretsId>
    <Nullable>enabled</Nullable>
    <AssemblyName>KrakenApiClient</AssemblyName>
    <RootNamespace>KrakenApiClient</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="README.md" Pack="true" PackagePath="\" />
    <EmbeddedResource Include="logo.png">
      <!--<Pack>True</Pack>
      <PackagePath></PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>-->
    </EmbeddedResource>
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="api response models.fs" />
    <Compile Include="utils.fs" />
    <Compile Include="responses.fs" />
    <Compile Include="parser.fs" />
    <Compile Include="currency mapper.fs" />
    <Compile Include="IClient.fs" />
    <Compile Include="Client.fs" />
  </ItemGroup>
  
  <ItemGroup />

  <ItemGroup>
    <PackageReference Include="Alex75.Cryptocurrencies" />
    <PackageReference Include="CommunityToolkit.Diagnostics" />
    <PackageReference Include="Flurl.Http" />
    <PackageReference Include="FSharp.Data" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Update="FSharp.Core" />
  </ItemGroup>

</Project>
