<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Example</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alex75.Cryptocurrencies" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KrakenApiClient\KrakenApiClient.fsproj" />
  </ItemGroup>

</Project>
