name: 🚀 Deploy http-client branch

on:
  push:
    branches: [""http-client""]

env:
  PROJECT_FOLDER: src/KrakenApiClient
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout code
      uses: actions/checkout@v5
  
    - name: 🆕 Create Version
      id: versioning
      run: | 
        VERSION=$(date +'%y.%-m.%-d')-${{ github.run_number }}
        # create OUTPUT variables for next steps
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_ENV  # Enables $VERSION below

    - name: ⚙️ Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: 🔍 Whhich branch is this?
      run: 
        #echo "Branch: ${{ github.ref }}"
        echo github.ref:: ${{github.ref}}

    - name: 🔄 Restore packages
      run: dotnet restore

    - name: 🏗️ Build
      run: dotnet build --configuration Release --no-restore

    - name: 🧪 Run Tests
      run: |
        dotnet test --no-restore --configuration Release --logger "GitHubActions"
        --filter "TestCategory!=SKIP_ON_DEPLOY & TestCategory!=REQUIRES_API_KEY"
     
    - name: 🎯 Define NuGet package version
      run: |
        suffix="-alpha"
        # remove the suffix if we are pushing from main branch
        if [[ ${{ github.event_name }} == "push" && ${{ github.ref }} == "refs/heads/main" ]]; then
          suffix=""
        fi
        echo version:: $VERSION$suffix
        echo "NUGET_PACKAGE_VERSION=$VERSION$suffix" >> $GITHUB_ENV
    
    - name: 📦 Pack NuGet
      run: |
        echo create package $NUGET_PACKAGE_VERSION
        dotnet pack $PROJECT_FOLDER --configuration Release --no-build 
        -p:PackageVersion=$NUGET_PACKAGE_VERSION
        -o ./nupkgs

    - name: 🚀 Publish NuGet
      run: |
        echo "publish $NUGET_PACKAGE_VERSION"
        dotnet nuget push ./nupkgs/*.nupkg 
          --api-key "${NUGET_API_KEY}" 
          --source https://api.nuget.org/v3/index.json 
          --skip-duplicate

