name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:  
  VERSION: 1.0.${{github.run_number}}
  PROJECT_FOLDER: Alex75.KrakenApiClient
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0.x'
#    - name: set user secrets to run tests
#      run: |
#        dotnet user-secrets list --id ${{ secrets.USER_SECRETS_ID }}
#        dotnet user-secrets --id ${{ secrets.USER_SECRETS_ID }} set "API name" ${{ secrets.KEY_NAME }}
#        dotnet user-secrets --id ${{ secrets.USER_SECRETS_ID }} set "API secret" ${{ secrets.KEY_SECRET }}
    - name: test
      run: |
        echo github.event_name  ((github.event_name )) [[github.event_name]]
        print github.event_name
        echo github.ref  ((github.ref))
        echo github.head_ref
        echo github.base_ref
        echo 
        suffix="-alpha"
        if [[ github.event_name == "push" ]]; then
          suffix=""
        fi
        echo $VERSION$suffix
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --filter "TestCategory!=SKIP_ON_DEPLOY & TestCategory!=REQUIRES_API_KEY"

    - name: Pack NuGet
      run: |         
        echo ${{ github.event_name }} ${{ github.ref }} #  github.event_name== 'push' && github.ref == 'refs/heads/main'
        echo create package $VERSION
        dotnet pack $PROJECT_FOLDER --configuration Release --no-build -p:PackageVersion=$VERSION
    - name: Publish NuGet
      run: |        
        suffix="-alpha"
        if [[ github.event_name == "push" ]]; then
          suffix=""
        fi
        echo $VERSION$suffix
    #  run: dotnet nuget push $PROJECT_FOLDER/bin/Release/*.nupkg  --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
