name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:  
  VERSION: 1.0.${{github.run_number}} 
  PROJECT_FOLDER: Alex75.KrakenApiClient
  NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: '6.0.x'

    - name: define package version
      id: package_version
      run: |        
        suffix="-alpha"
        if [[ $(( github.event_name )) == "push" && $(( github.ref )) == "refs/heads/master" ]]; then
          suffix=""
        fi
        echo version - $VERSION$suffix
        echo ::set-output name=version::$VERSION$suffix
        #$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --filter "TestCategory!=SKIP_ON_DEPLOY & TestCategory!=REQUIRES_API_KEY"

    - name: Pack NuGet
      run: |         
        echo create package ${{ steps.package_version.outputs.version }}
        dotnet pack $PROJECT_FOLDER --configuration Release --no-build -p:PackageVersion=$VERSION
    - name: Publish NuGet
      run: |        
        suffix="-alpha"
        if [[ $(( github.event_name )) == "push" && $(( github.ref )) == "refs/heads/master" ]]; then
          suffix=""
        fi
        echo $VERSION$suffix
        echo version $VERSION
        dotnet nuget push $PROJECT_FOLDER/bin/Release/*.nupkg  --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json

# how to pass values from step to step
# https://stackoverflow.com/questions/57819539/github-actions-how-to-share-a-calculated-value-between-job-steps